name: Readme-stats updater
on:
  workflow_dispatch:
jobs:
  generate_and_commit_cards:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Create assets directory if it doesn't exist
        run: mkdir -p assets
      - name: Download stats cards
        run: |
          cards=(
            "api|stats-dark.svg|show_icons=true&theme=holi&show=prs_authored,prs_merged,prs_merged_percentage"
          )
          for card in "${cards[@]}"; do
            IFS="|" read -r endpoint output params <<< "$card"
            curl --fail --location \
            "https://github-stats-extended-silk.vercel.app/${endpoint}?username=${{ github.repository_owner }}&${params}" \
            -o "assets/${output}"
          done
      - name: Commit downloaded cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/*.svg
          git commit -m "Update README cards" || exit 0
          git push