name: Readme-stats updater
on:
  workflow_dispatch:
jobs:
  generate_and_commit_cards:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Download stats card
        run: |
          mkdir -p assets
          curl --fail --location \
          "https://github-stats-extended-silk.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&theme=holi&show=prs_authored,prs_merged,prs_merged_percentage" \
          -o assets/stats-dark.svg
      - name: Commit downloaded cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/*.svg
          git commit -m "Update README cards" || exit 0
          git push